#!/bin/bash

set -x
set -e

if [ ! -f python3.14 ]; then
    wget -O python3.14 https://github.com/niess/python-appimage/releases/download/python3.14/python3.14.0rc2-cp314-cp314-manylinux2014_x86_64.AppImage
    chmod 755 python3.14
fi

if [ ! -d AppDir ]; then
    ./python3.14 --appimage-extract
    mv squashfs-root AppDir
    rm AppDir/AppRun AppDir/python*
    cp assets/appimage/* AppDir
fi

cd AppDir
./opt/python3.14/bin/python3.14 -m pip install -U --target missilecommand git+https://github.com/dickerdackel/missilecommand
cd ..
appimagetool AppDir
